### PR TITLE
orthogonal_projection: Improve documentation

### PR DESCRIPTION
**Pull request by Makman2**
Simple documentation improvement^^

### CODE REVIEW

**Comment by sils1297** [comment]
you wouldn't accidentally care for a review of my big PR of coala (150)?
I'm waiting since quite some time to get everything on master.

2015-01-18 21:27 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
It's hard to review code you really don't understand. I already reviewed some files but found nothing more since the last time^^

**Comment by sils1297** [comment]
As I said you already found more than the others. Could you give me a range
of commits you've looked at? Then I can merge them.

2015-01-18 21:37 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
I looked until
f49ceb1: ConfWriter: Simplify __write_key_val()
But I can't guarantee that I missed some errors (especially semantic ones because I don't know exactly what each function does :>).

**Comment by Makman2** [comment]
I'll review yours further tomorrow^^

**Comment by sils1297** [comment]
If it is not clear what the function does you can ask and I'll improve
documentation. I'm setting for highest quality standards for this code so
it shouldn't be a difficult task to understand it. Also if there's some
special case I didn't test feel free to mention. You can't make a guarantee
by the way if you do not mathematically prove the correctness of the code
which is a monumental task.

2015-01-18 21:46 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
Thanks thats great :)

2015-01-18 21:52 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Pull request merged**
