### PR TITLE
Wip/coala

### PR DESCRIPTION
**Pull request by sils1297**
I didn't put code check instructions into the readme yet because probably some settings/command line options will change in the next weeks and will need adjustement. But it works pretty well, setting up coala for this did take half a minute, I love it. (Ok, I wrote it. But still. I love it.)

### CODE REVIEW

**Comment by sils1297** [comment]
If you want to try out coala for curiosity I'd recommend:

```
git checkout 10359da
coala
```

assuming coala is installed. If you want to help us you can try this on windows but I don't expect this to work, though I don't know why. I did quite some effort to make all coala tests pass on windows (don't know if this is still the case) so everything should work somehow... it should work on linux without hassle.

**Comment by Makman2** [comment]
Because coala is under such active development maybe it's best to use it as a submodule. Then you can write instructions into the README how to use it, since only the specific commit is checked out defined in the submodule.

**Comment by sils1297** [comment]
Good idea, done. Drawback is that I'll need to update the coala submodule from time to time but we'll all use the same version and there's no need to install coala which makes the code checking pretty simple.

**Comment by Makman2** [comment]
That's right but then you have the working version with our project.
I'll check how coala works today :)

**Comment by sils1297** [comment]
cool, if you need more info, check out the TUTORIAL.md in the coala main repository.

**Comment by Makman2** [comment]
Hm interesting thing: Under my Ubuntu 14.04 VM if I cancel coala with CTRL+C, my prompt vanishes^^
Came because I accididentally ran coala in it's own directory and it checked everything there. Shall I create an issue in your repo?

**Comment by Makman2** [comment]
Ah okay, if I CTRL+C again the program aborts (but with hard exceptions). That should be fixed^^

**Comment by Makman2** [comment]
PS: Would you mind to put the submodule into a `submodule` directory? That makes the root dir cleaner^^

**Comment by sils1297** [comment]
The Ctrl+C thing is a bug. Reason is that we spawn up several processes so if the user aborts we'll have to show some message "Aborting run..." and cancel all processes gracefully. See https://github.com/coala-analyzer/coala/issues/242

**Comment by Makman2** [comment]
And next issue for coala: I tried the SpaceConsistencyBear and my options are like these:
```
1: Open the file in an editor.
2: Apply the patch automatically.
0: No action.
```
`No action` should be on top of the listing, 1 2 and then 0 is quite confusing :P

**Comment by sils1297** [comment]
You can file that as an issue. Reasoning was that you can read through your available, useful, actions top down but can choose no action with the same key every time.

**Comment by sils1297** [comment]
its only one submodule. Having a directory just to hold  another directory doesn't save any space. I'd totally agree if there were several submodules in CE3D.

**Comment by Makman2** [comment]
I think that increases the logical structure of root. First you don't know what coala is, but if it's inside the submodules you know "Ah okay, it's a submodule". At first glance you may think that this is an hard embedded component.
I did the same here: https://github.com/Makman2/GameBox

Coala PS :D
What about a message if coala can't find anything instead of just returning?

**Comment by sils1297** [comment]
I'd recommend you file all your complaints for coala as issues there, I'll resolve duplicates and answer you there, then we don't push this PR full with nonrelevant stuff. (It is no secret that coala is experimental but I think for its stage its quite usable.)

**Comment by Makman2** [comment]
Good thing, already forgot to do so :)

**Comment by sils1297** [comment]
here you've got yuour submodule subdirectory

**Pull request merged**
