### PR TITLE
Implement line-drawing in console-renderer

### PR DESCRIPTION
**Pull request by Makman2**
The console renderer now supports drawing lines.
This pull requests also corrects some aesthetic failures.

### CODE REVIEW

**Comment by Makman2** [comment]
Rebased^^

**Comment by sils1297** [comment]
ok, everything should be mergeable by now

**Comment by sils1297** [comment]
I'll let you do the merge, you should know this better.

**Comment by Makman2** [comment]
I want to test the Z-buffer algorithm manually first, after that I'm going to merge^^

**Comment by sils1297** [comment]
good, see? I missed that ;)

2015-01-15 0:05 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
It was a good idea to test it manually... I did some quite big mistakes...
So that will give a rebase, but you only need to ack the commit that involves the line drawing again^^

**Comment by Makman2** [comment]
Better idea: I'll push a fixup commit that you can ack, if you acked it then I'll rebase and merge^^

**Comment by Makman2** [comment]
Now it's working.

**Comment by Makman2** [comment]
```
pick 12fe596 renderer/console: Use Z-Buffer in DrawLine()
fixup 9673929 FIXUP WITH 12fe596: Fix z-buffer usage
fixup 7c6260d FIXUP WITH 12fe596: Resort z-buffer variables
pick 96890dd codestyle: Add advised style note
```

**Comment by Makman2** [comment]
Okay that's it, merging.

**Comment by sils1297** [comment]
Cool! Do you have a master plan on how we get CE3D into a usable state?
What's missing? That is long overdue IMO.
Am 18.01.2015 18:57 schrieb "Makman2" <notifications@github.com>:

**Comment by Makman2** [comment]
De facto you can use it, but the Orthogonal Projection is missing some features to make it work in all dimensions (the world's up thing, but I have problems to bringt it together with the lookat vector).
If this is done we can announce v0.1 :D

**Comment by sils1297** [comment]
Then you should update instructions on how to build and execute the thing
plus a mini example application. You can probably extend the one I wrote
back then.

2015-01-18 21:01 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Good thing, will do that

**Pull request merged**
